version: "3.9"

services:
  api:
    build: .
    container_name: trading-api
    volumes:
      - .:/app # כל הפרויקט מועתק ל־/app
      - ./data:/app/data # data צריך להיות תחת /app בתוך הקונטיינר
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
