"""Add duration_days to trades

Revision ID: 9503ac2d53e0
Revises: a5ceff34f9bf
Create Date: 2025-06-02 15:42:07.719265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9503ac2d53e0'
down_revision: Union[str, None] = 'a5ceff34f9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_pct', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reason_entry', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('estimates', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stop_loss', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('reason_exit', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('reason_exit')
        batch_op.drop_column('stop_loss')
        batch_op.drop_column('estimates')
        batch_op.drop_column('reason_entry')
        batch_op.drop_column('portfolio_pct')

    # ### end Alembic commands ###
