"""init

Revision ID: a5ceff34f9bf
Revises: 
Create Date: 2025-05-28 18:53:08.761821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ceff34f9bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('date', 'symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('pnl_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_intraday', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_id'), ['id'], unique=False)
        batch_op.create_index('ix_trades_symbol_entry_date', ['symbol', 'entry_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_symbol_entry_date')
        batch_op.drop_index(batch_op.f('ix_trades_id'))

    op.drop_table('trades')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('market_data')
    # ### end Alembic commands ###
